# Generated by Django 3.1.7 on 2021-03-28 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_Posted',
            new_name='date_posted',
        ),
    ]
